hw 1
Naniduan/formal-lang-course pull request #1
Opened 2023-09-13 23:30 UTC by Naniduan

## Задача

- [x] Сделать `fork` данного репозитория.
- [x] Добавить ссылку на ваш `fork` в [таблицу](https://docs.google.com/spreadsheets/d/1-vx82auNr0PQDQ3SwA7IYewZyOC9iHIaoX1w1qRUZ3I/edit?usp=sharing).
- [ ] Добавить в совладельцы форка одного из ассистентов (чтобы узнать, кого именно, нужно посмотреть в [таблицу](https://docs.google.com/spreadsheets/d/1-vx82auNr0PQDQ3SwA7IYewZyOC9iHIaoX1w1qRUZ3I/edit?usp=sharing))
- [x] Реализовать модуль, предоставляющий перечисленные ниже возможности. Для работы с графами использовать [cfpq-data](https://formallanguageconstrainedpathquerying.github.io/CFPQ_Data/tutorial.html#graphs). Данный модуль в дальнейшем будет расширяться. Функции, которые необходимо реализовать:
  - [x] По имени графа вернуть количество вершин, рёбер и перечислить различные метки, встречающиеся на рёбрах. Для получения графа по имени использовать [эту функцию](https://formallanguageconstrainedpathquerying.github.io/CFPQ_Data/tutorial.html#get-a-real-graph).
  - [x] По количеству вершин в циклах и именам меток строить [граф из двух циклов](https://formallanguageconstrainedpathquerying.github.io/CFPQ_Data/reference/graphs/generated/cfpq_data.graphs.generators.labeled_two_cycles_graph.html#cfpq_data.graphs.generators.labeled_two_cycles_graph) и сохранять его в указанный файл в формате DOT (использовать pydot).
- [x] Добавить необходимые тесты.
- [x] Добавить запуск тестов с помощью `pytest` в `.github/workflows/`.

2023-09-21 19:25 UTC, rustam-azimov requested changes

2023-09-21 19:25 UTC, rustam-azimov commented on project/graph_utils.py
> +    return nodes, edges, labels
Здесь лучше named tuple или какой то класс создать вроде GrpahInfo

2023-09-21 19:25 UTC, rustam-azimov commented on project/graph_utils.py
> +def get_graph_stats(graph_name):
В этом задании и далее для каждой функции и класса пишите пожалуйста докстринги.

2023-09-22 20:49 UTC, Naniduan commented on project/graph_utils.py
> +    return nodes, edges, labels
Добавил

2023-09-22 20:49 UTC, Naniduan commented on project/graph_utils.py
> +def get_graph_stats(graph_name):
Добавил

2023-09-23 18:18 UTC, rustam-azimov approved these changes

2023-09-23 19:50 UTC, merged